### ISSUE TITLE
Social Sciences materials?

### ISSUE THREAD

**Issue by lexnederbragt** [datacarpentry/datacarpentry.github.io#215]
http://www.datacarpentry.org/lessons/ mentions "Social science materials" but these are not listed there?

**Comment by ErinBecker** [comment]
Good catch! It looks like those got taken off of the website. I'll remove the reference.

**Comment by ErinBecker** [comment]
@lexnederbragt We had a single module for data mining with social sciences data, but since this is not a complete workshop offering, they were removed from the lessons page. 

We do have a full workshop for social sciences in development: https://github.com/data-lessons (gapminder-R, gapminder-spreadsheet, gapminder-openrefine).
