### ISSUE TITLE
List of workshops out of date

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#416]
The list of upcoming workshops lists past workshops.
Also not all upcoming workshops published in AMY show up here.

**Comment by tracykteal** [comment]
Thanks @maneesha I'll do a manual update, and look to see why it's not auto-updating.

**Comment by tracykteal** [comment]
Workshops have been updated. I was running a cron job to do the updates, and something changed with that server. I'll move the cron job over to a more centralized server. Keeping this issue open for that update.

**Comment by maneesha** [comment]
We still have workshops that are not showing up on the DC website.  @tracykteal  let me know if there is anything I can do to help fix this.

**Comment by maneesha** [comment]
Bumping this up as I'm again getting inquiries about workshops not displaying.  The workshop list continues to be out of date. 
@tracykteal  Let me know what I can do to fix this.

**Comment by maneesha** [comment]
@tracykteal  where do I run this script from?

**Comment by tracykteal** [comment]
It's the 'amy_add.sh' script in the top level of this repo

**Comment by maneesha** [comment]
I don't have the same environment set up so I get this error:
```
/anaconda/bin/python3.5m bin/get-amy.py -u https://amy.software-carpentry.org/api/v1/ -o _data/amy.yml --tags-any=DC
make: /anaconda/bin/python3.5m: Command not found
Makefile:11: recipe for target 'amy' failed
make: *** [amy] Error 127
```

**Comment by maneesha** [comment]
bumping this up @tracykteal  please see my comment above from last week

**Comment by fmichonneau** [comment]
I regenerated the list of workshops, and it's now up to date on the website.

However, the script currently included in the repository seems out of date. I used the one included in the Software Carpentry repository. This script requires AMY credentials to retrieve the data. 

I suggest we use a daily CRON job on travis to do build the workshop list, so when things break we'll be able to diagnose issues more easily and be notified about it.

@jduckles Should we assume the script included in the SWC website repo is always up to date and always pull it from there? alternatively, we could have a repository dedicated for this script.

**Comment by jduckles** [comment]
This is done here, as of yesterday: https://github.com/carpentries/amy-feeds

**Comment by libcce** [comment]
@jduckles When you have the time, can you add a feed for LC as well?  Thanks!

**Comment by maneesha** [comment]
This is out of date.  As of today, June workshops are still listed.  It should also be in chronological order.  It's currently in reverse chronological order.  pinging @jduckles

**Comment by maneesha** [comment]
This is not just on the front page but on this page as well:  http://www.datacarpentry.org/workshops-upcoming/

Workshops from June 2018 show up on this page.

**Comment by jduckles** [comment]
The process for updating `data/amy.yml` is not automated in this repo. See above: https://github.com/datacarpentry/datacarpentry.github.io/issues/416#issuecomment-399058669
I don't think we should keep the `.yml` in the repo as it has instructor email addresses in it, the yml in the swcarpentry repo is not kept up-to-date and instead is pulled down at build-time.

There are a couple of ways we can go:
1. Someone periodically updates amy.yml in this repo (what Francois did above)
1. A cron job pushes an updated version of `amy.yml` (see [this file](https://github.com/carpentries/amy-feeds/blob/master/bin/get-amy.py) for how to do that with AMY authentication.
1. We adapt the feeds pages to pull from [amy-feeds](https://github.com/carpentries/amy-feeds) JSON files instead of building from `yaml`. (may require us to have copies of that JSON hosted at a *.datacarpentry.org subdomain because of XSS browser security). This is my eventual plan for `carpentries.org`

**Comment by fmichonneau** [comment]
I've set up a travis script that pulls the workshop data from the same makefile that generates the amy-feeds. It will run after each push to the repo and is on a weekly cron job that runs unless there has been updates in the last 24 hours.

Getting the data from amy-feeds could be simplified once we either create a YAML file for the workshops hosted on carpentries.org, or update the website template so that it can parse the JSON file provided by amy-feeds.

**Comment by fmichonneau** [comment]
@maneesha the workshops are also now listed in chronological order on the front page and in the upcoming workshops page.
